version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: poll
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: poll
      DB_USER: user
      DB_PASSWORD: pass
    depends_on:
      - db

volumes:
  pgdata: