apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    CREATE TABLE polls (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL
    );

    CREATE TABLE options (
        id SERIAL PRIMARY KEY,
        poll_id INT REFERENCES polls(id),
        text TEXT,
        votes INT DEFAULT 0
    );